const dataSlugs = [
  {
    id: '2016-2017',
    images: [
      {
        pictureId: 1,
        img: '../../images/1.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30x30',
        year: '2019',
      },
      {
        pictureId: 2,
        img: '../../images/2.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30 x 35',
        year: '2019',
      },
      {
        pictureId: 1,
        img: '../../images/1.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30x30',
        year: '2019',
      },
      {
        pictureId: 2,
        img: '../../images/13.png',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30 x 35',
        year: '2019',
      },
      {
        pictureId: 1,
        img: '../../images/1.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30x30',
        year: '2019',
      },
      {
        pictureId: 2,
        img: '../../images/2.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30 x 35',
        year: '2019',
      },
      {
        pictureId: 1,
        img: '../../images/1.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30x30',
        year: '2019',
      },
      {
        pictureId: 2,
        img: '../../images/2.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30 x 35',
        year: '2019',
      },
      {
        pictureId: 1,
        img: '../../images/1.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30x30',
        year: '2019',
      },
      {
        pictureId: 2,
        img: '../../images/2.jpg',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '30 x 35',
        year: '2019',
      },
    ],
  },
  {
    id: '2017-2019',
    images: [
      {
        pictureId: 3,
        img: '../../images/5.png',
        title: 'g8 sa',
        technique: 'oil on canvas',
        size: '260 x 81',
        year: '2019',
      },
      {
        pictureId: 4,
        img: '../../images/6.png',
        title: 'XZ',
        technique: 'oil on canvas',
        size: '30 x 20',
        year: '2018',
      },
      {
        pictureId: 5,
        img: '../../images/7.png',
        title: '/',
        technique: '/',
        size: '/',
        year: '2018',
      },
      {
        pictureId: 6,
        img: '../../images/8.png',
        title: '/',
        technique: '/',
        size: '/',
        year: '2018',
      },
    ],
  },
  {
    id: '2020-',
    images: [
      {
        pictureId: 5,
        img: '../../images/3.png',
        title: 'Untitled',
        technique: 'oil and monoprint on canvas',
        size: '73 x 52.5',
        year: '2020',
      },
      {
        pictureId: 6,
        img: '../../images/4.png',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '52.5 x 41',
        year: '2021',
      },
      {
        pictureId: 7,
        img: '../../images/9.png',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '67.5 x 61.3',
        year: '2021',
      },
      {
        pictureId: 8,
        img: '../../images/10.png',
        title: 'Untitled',
        technique: 'oil on canvas',
        size: '71 x 53.5',
        year: '2021',
      },
      {
        pictureId: 9,
        img: '../../images/13.png',
        title: 'Untitled',
        technique: 'acrylic and monoprint on canvas',
        size: '71 x 53.5',
        year: '2021',
      },
      {
        pictureId: 10,
        img: '../../images/12.png',
        title: 'Untitled',
        technique: '/',
        size: '/',
        year: '2021',
      },
    ],
  },
];

export default dataSlugs;
