const dataSlugs = [
  {
    id: '2016-2017',
    images: [
      {
        pictureId: 1,
        img: '../../images/2016-1.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2016',
      },
      {
        pictureId: 2,
        img: '../../images/2016-2.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2016',
      },
      {
        pictureId: 3,
        img: '../../images/2016-3.png',
        title: '',
        technique: 'acrylic and print on canvas',
        size: '',
        year: '2016',
      },
      {
        pictureId: 4,
        img: '../../images/2016-4.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2016',
      },
      {
        pictureId: 5,
        img: '../../images/2016-5.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2016',
      },
      {
        pictureId: 6,
        img: '../../images/2016-6.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2016',
      },
    ],
  },
  {
    id: '2017-2019',
    images: [
      {
        pictureId: 7,
        img: '../../images/2019-1.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2019',
      },
      {
        pictureId: 8,
        img: '../../images/2019-2.png',
        title: '',
        technique: '',
        size: '',
        year: '',
      },
      {
        pictureId: 9,
        img: '../../images/2019-3.jpg',
        title: '',
        technique: '',
        size: '',
        year: '',
      },
      {
        pictureId: 10,
        img: '../../images/2019-4.png',
        title: '',
        technique: '',
        size: '',
        year: '',
      },
      {
        pictureId: 11,
        img: '../../images/2019-5.png',
        title: '',
        technique: '',
        size: '',
        year: '',
      },
      {
        pictureId: 12,
        img: '../../images/2019-6.png',
        title: 'g8 sa',
        technique: 'oil on canvas',
        size: '260 x 81cm',
        year: '2019',
      },
      {
        pictureId: 13,
        img: '../../images/2019-7.png',
        title: 'XZ',
        technique: 'oil on canvas',
        size: '30 x 20cm',
        year: '2018',
      },
      {
        pictureId: 14,
        img: '../../images/2019-8.png',
        title: '',
        technique: '',
        size: '',
        year: '',
      },
      {
        pictureId: 15,
        img: '../../images/2019-9.png',
        title: '',
        technique: 'oil on canvas',
        size: '',
        year: '2018',
      },
      {
        pictureId: 16,
        img: '../../images/2019-10.png',
        title: '',
        technique: 'oil on canvas',
        size: '100 x 150cm',
        year: '2017',
      },
    ],
  },
  {
    id: '2020-',
    images: [
      {
        pictureId: 17,
        img: '../../images/2020-1.png',
        title: '',
        technique: 'oil and monoprint on canvas',
        size: '73 x 52.5cm',
        year: '2020',
      },
      {
        pictureId: 18,
        img: '../../images/2020-2.png',
        title: '',
        technique: 'oil on canvas',
        size: '52.5 x 41cm',
        year: '2021',
      },
      {
        pictureId: 19,
        img: '../../images/2020-3.png',
        title: '',
        technique: 'oil on canvas',
        size: '67,5 x 61.3cm',
        year: '2021',
      },
      {
        pictureId: 20,
        img: '../../images/2020-4.png',
        title: '',
        technique: 'acrylic and graphit on canvas',
        size: '71 x 53.5cm',
        year: '2021',
      },
      {
        pictureId: 21,
        img: '../../images/2020-5.png',
        title: '',
        technique: 'acrylic and monoprint on canvas',
        size: '71 x 53.5cm',
        year: '2021',
      },
      {
        pictureId: 22,
        img: '../../images/2020-6.png',
        title: '',
        technique: 'acrylic and monoprint on canvas',
        size: '71 x 53.5cm',
        year: '2021',
      },
      {
        pictureId: 23,
        img: '../../images/2020-7.png',
        title: '',
        technique: '',
        size: '',
        year: '2021',
      },
    ],
  },
];

export default dataSlugs;
